name: Access files
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Check the contents of the file
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v1
      - run: cat sample.txt
